name: python CI

on:
  push:
    branches: [ "master" ]


env:
  PYTHON_VERSION: 3.9.6

jobs:
  build:
    name: build-docker-image
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:13.1
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{env.JAVA_VERSION}}
        cache: maven
    - name: Run Tests
      run: mvn -f pom.xml clean package -P test